### PR TITLE
Menu button fixes

### PR DESCRIPTION
**Pull request by Excellify**
Fixed an issue with the emote menu being a few pixels too large and not clickable on the sides outside the logo.
Made the 7TV settings button have a background on hover.

### CODE REVIEW

**Review by AnatoleAM — COMMENTED** [review]
This is good, but is there a reason the class name was changed?

**Comment by Excellify** [comment]
Changed the name because i used the style for both the emote menu button and the settings button

**Comment by AnatoleAM** [comment]
Oh right that's correct, this is used in both the navigation bar and chat so the change makes sense.

**Review by AnatoleAM — APPROVED** [review]

**Comment by Excellify** [comment]
Also looked at adding a tooltip to the settings button, similarly to the other buttons up there. And maybe making the open settings button toggle the settings window.

**Comment by AnatoleAM** [comment]
I think a tooltip would require making a custom one, I haven't figured out how to access twitch's tooltip

**Comment by Excellify** [comment]
A very similar tooltip to twitch's can be made with just some css, started messing around with it but didn't get it done. FFZ's tooltip is not identical to twitch's either.

**Pull request merged**
